language: bash
os: linux
dist: trusty

cache:
  directories:
    - $HOME/astyle

git:
  depth: false
  submodules: false

before_install:
  - git submodule update --init

stages:
  - build
  - deploy

jobs:
  include:
    # Build stage. To save time, run all kinds of builds and tests in parallel.
    #
    # TODO: since we can now call different script for each job,
    # split the do-it-all common.sh into separate scripts responsible
    # for different types of jobs below:

    # Deploy stage.
    # Here we build the package JSON (always) and do the deployments
    - name: "Package / deploy"
      stage: deploy
      script: $TRAVIS_BUILD_DIR/tests/common.sh
      env: BUILD_TYPE=package
      if: env(CI_GITHUB_API_KEY) IS present
      deploy:
      # Create Github release, upload artifacts
      - provider: releases
        draft: true
        skip_cleanup: true
        api_key:
          secure: kYsxX/N21fwLSTLpbb0c96PnQHn1CIMqZstm02hfUhCX83FygWSh4vs3gzW28DMpjQMZ6vC4g+jtfosYU2tUhht/bynurDH4edpEyGeMyK+fzCI9pAr4JT0RbKQI84EC18ScpgP/UP0jTc1LJ+xl8UMwSiDE0mzHx7xJ4mMNQbA=
        file_glob: true
        tag_name: $TRAVIS_TAG
        target_commitish: $TRAVIS_COMMIT
        file:
          - package/versions/$TRAVIS_TAG/esp8266-$TRAVIS_TAG.zip
          - package/versions/$TRAVIS_TAG/package_esp8266com_index.json
        on:
          repo: esp8266/Arduino
          tags: true

      # Update the package index URL to point to the new version
      - provider: script
        skip_cleanup: true
        script: bash package/deploy_package_index.sh $CI_GITHUB_API_KEY
        on:
          repo: esp8266/Arduino
          tags: true

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - secure: "dnSY+KA7NK+KD+Z71copmANDUsyVePrZ0iXvXxmqMEQv+lp3j2Z87G5pHn7j0WNcNZrejJqOdbElJ9Q4QESRaAYxTR7cA6ameJeEKHiFJrQtN/4abvoXb9E1CxpL8aNON/xgnqCk+fycOK3nbWWXlJBodzBm7KN64vrcHO7et+M="
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
